### ISSUE TITLE
v případě \neq na konci řádku se na začátku dalšího řádku vypíše =

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#1]
@Pikoš 

Nemám teď bohužel čas to řešit. Ale vyřešeno je to například v tomto balíku:
http://joomup.com/rumathbr.sty

![screenshot](https://cloud.githubusercontent.com/assets/1250507/15453411/73205d7e-2015-11e6-9231-c1915d154d67.png)

**Comment by LukasLedvina** [comment]
@Werkov 
Ten ruský balík by to mohl řešit. Nezkoušel jsem ho, ale zdrojáky tvoří
docela zanořené definice pomocných maker (\SetBreakableRel) a pak dlouhé
výčty jejich aplikací.

Brát ten balíček celý by asi ovlivnilo příliš mnoho jiných zalamování.
Extrakt (patrně ne malá) těch principiálních maker by to mohl řešit.

**Comment by LukasLedvina** [comment]
@Pikoš

ten rumathbr.sty, který jsem posílal, toho skutečně rozbíjí hodně. Nezkoušel jsem to na FYKOSím ročníku, ale na diplomce (kde ale fkssugar používám, takže podobně by dopadl i FYKOS) a rozsypala se hodně.

O něco méně se rozsypala při použití tohoto (nezkoumal jsem, jak moc se to liší):
https://github.com/dryabov/rmathbr/blob/master/rmathbr/rmathbr.sty
Co jsem si při zběžném pohledu všiml, že se rozbilo:
 - \C, \dg, \conj (pravděpodobně by stačilo upravit definici)
 - \_ a \^ - ty index jsou podstatně větším písmem než by měly být
Ale jinak se mi ten balík líbí, protože umožňuje zalomení rovnice i v jiném místě než v =.

**Comment by LukasLedvina** [comment]
@Pikoš

kdo chce, může vyzkoušet, je to ve větví pikos-rmathbr. Na Debianu si doinstalujte texlive-generic-extra.

Ale určitě to není v této podobě vhodné k nasazení. Problémy, které jsem psal v minulém e-mailu, jsou sice asi odstraněny, ale například \ce{CO2} vytvoří obrovský index.

**Comment by LukasLedvina** [comment]
Jedno řešení může být dev-fkssugar-neq: 38a21c270, které asi nic nerozbíjí a opravuje špatně opakující se `\neq` tak, že na `\neq` se rovnice nikdy nezlomí.

**Comment by Werkov** [comment]
Upravil jsem test `t005`, aby se to tam projevavalo (asi změna velikosti papíru?) a otestoval funknčnost řešení z `dev-fksssugar-neq`. Je to lepší, než co máme, takže jsem to mergeoval do `dev`.
