### ISSUE TITLE
Číslování testů

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#10]
Chceme, aby každý test měl své unikátní číslo, či aby skupina testů (jedné věci) měla jedno číslo?

Narážím na testy 007-009, které všechny testují angličtinu. Dále pak na zatím neexitující test na qed v beameru, který bude mít výrazně větší číslo než 010-qed, ačkoli spolu velmi těsně souvisejí.

**Comment by Werkov** [comment]
Číslo testu bych bral jen jako nevýznamový identifikátor, který shodou okolností určuje pořadí spouštění testů.

Ano, bylo by hezké mít související testy pohromadě, ale tahle struktura moc neumí insert doprostřed, tak jsem to u 010-qed neřešil. Právě proto, že to číslo nemá skoro žádný význam.

**Comment by Werkov** [comment]
Zavírám, neboť to nepůsobí problém. Pokud by to změnilo, můžeme to znovuotevřít.
