### ISSUE TITLE
Odkaz na footnote

### ISSUE THREAD

**Issue by Werkov** [fykosak/fks-texmf#15]
Od Krásný Kuba:

> snažím se udělat odkaz na footnote, abych neměl dvě stejné poznámky pod čarou,
> ale nic jako \footref{} ani \fotenotemark[\ref{}], které jsem našel na
> internetu mi nefunguje. Existuje nějaká fykos-kompatibilní metoda k tomuto?

**Comment by LukasLedvina** [comment]
Ahoj,

funkční řešení zde.

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
                                                                                                                                                                                                                                                                                
\begin{document}
\newcommand\footnoteref[2]{%
\refstepcounter{footnote}\addtocounter{footnote}{-1}% VERY UGLY!!!!
\label{#1}%
\footnote{#2}%
}

Ahoj\footnoteref{xxxL}{xxx}

Reference na footnote \ref{xxxL} je tady\textsuperscript{\ref{xxxL}}.

\end{document}
```

**Comment by timkol** [comment]
Mně se to řešení nelíbí, přestane fungovat pokud budou v textu reference v pořadí foot1 foot2 foot1, navíc to v tu chvíli nehodí chybu, ale projde to a bude to špatně vysázeno.

**Comment by rzehumat** [comment]
Znovu aktuální. Lukášovo řešení zřejmě funguje, ale
1. není v makrech,
2. `footnoteref` by se měl jmenovat spíš `footnotelabel`,
3. `\textsuperscript{\ref{xxxL}}` by se měl jmenovat `\footnoteref{xxxL}`,
4. vytvořit i protejšky `footnotelabeli` a `footnoterefi` (nad diakritikou),
5. v kombinaci s hyperref se `\textsuperscript{\ref{xxxL}}` odkazuje na místo, kde je první zmínka (`footnoteref`) - ale my chceme, aby to ukazovalo dolů (přidejte k Lukášově ukázce `\usepackage{hyperref}` a uvidíte, co myslím.

**Comment by rzehumat** [comment]
Navržený pull request řeší 1-4, neřeší 5.
