### ISSUE TITLE
Diskuse k vyfuk-dev

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#16]
Ahoj,
- nelíbí se mi commit `e01eded058` "Nové logo matfyzu". Důvodem je to, že může rozbít docela hodně věcí, např. sazbu diplomů fyziklání a fyziklání online. Navrhuji přidat noé logo jako nový soubor a tam, kde se má použít jej použít explicitně.
- fakt se nikde nepoužívá `\maketitlenew` ?
- merge `7ba1ee4c` je fakt hodně podezřelý, vypadá to, že by `vyfuk-dev` měl být spíše na `1531b350`.

Lukáš

**Comment by Auratons** [comment]
Ahoj,

- přidal jsem matfyz_nove_logo.eps a změnil jsem ten obrázek jen u výfučí brožurky. Nicméně by asi Fykos měl na toto logo také pomalu přejít.
- \maketitlenew se opravdu nepoužívá nikde, grepoval jsem to všude a Mišo říkal, že to pravděpodobně dělal on a byla to slepá ulička.
- Vzhledem k tomu, že jsem to všechno dělal nově ve větvi ficury_vyfuk (:D), tak tenhle problém odpadl. Snažil jsem se taktéž přesněji pojmenovávat commity, třeba jakých seminářů se týkají.

Snad to je ok, už je to pushnuté a rozběhl jsem testy, ty bude třeba updatnout, jak jsem předpokládal.

Tom

**Comment by Werkov** [comment]
- mergeováno do `dev` (release až bude třeba || po hackathonu)
- `tests/exp-res/t003-simple-batch-1.png` regenerován s novou Výfučí hlavičkou
- větev `ficury_vyfuk` je moc pěkně udělaná -- atomické commity s popisnými zprávami, i vysvětlivky v kódů jsou patřičné :+1:

**Comment by Werkov** [comment]
Releasnuto.
fks-tex-base                               2.5-30-g542e384
