### ISSUE TITLE
Jazyková nastavení

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#17]
Přepsal jsem fkslang tak, aby jazyk se bral z `classOption`. Tento jazyk dostane jak `fkssugar.sty`, tak i `\selectdefaultlanguage`.

Prosím o merge `dev-fkslang`.

**Comment by Werkov** [comment]
Mergnuto, vybuilděno a nainstalováno na Astrid.

> fks-tex-base                                                   2.5-14-g53ae2e2
