### ISSUE TITLE
Vícejazyčnost oddělovače tisíců

### ISSUE THREAD

**Issue by timkol** [fykosak/fks-texmf#18]
S Meggy jsme řešili vícejazyčnost oddělovače tisíců. Jeden návrh je v uvozovkovém makru předefinovat makro \, druhý návrh byl vytvořit nové makro, které by v cs verzi bylo \, a v en verzi ,

**Comment by Werkov** [comment]
On Sat, Oct 29, 2016 at 12:41:09PM -0700, timkol <notifications@github.com> wrote:
> druhý návrh byl vytvořit nové makro, které by v cs verzi bylo \, a v en verzi ,
Tohle by nebylo zpětně kompatibilní, co?

Ta první varianta omezená na uvozovkové makro by snad nic rozbít/omezit
nemusela (anebo se \, používá i jinak než jako oddělovač řádů?)

**Comment by LukasLedvina** [comment]
Ahoj,
`\,` se používá v "makru i když si někdo potřebuje ručně vysázet jednotku. A pak je žádané chování, aby v libovolně jazyčné sazbě se sázela vždy mezera.

Když bychom na to bývali mysleli o trošku dříve, tak by šlo říci, že ve zdrojáku tečka je desetinná a čárka je na oddělování tisíců. Na druhou stranu tohle by spousta lidí pletla a bylo by to na zabití.

Kloním se k nějakému znaku, který se v "makru `catcode`ne na aktivní, jako tomu je např. u `e` a mezery, co byste řekli na `~`? Není to vhodné z hlediska hledání původu warningů `Nobreak space invalid in math mod` (nebo nějak podobně). Nebo nějaký podobný jiný...

**Comment by Werkov** [comment]
Anebo to udělat automaticky, tak jak to dělá např. siunitx [1] anebo
numprint [2].

(Vždycky jsem si myslel, že to parsování bude pomalé, ale nikdy jsem to
skutečně neměřil.)

[1]
ftp://ftp.dante.de/tex-archive/macros/latex/exptl/siunitx/siunitx.pdf

[2]
http://ftp.cvut.cz/tex-archive/macros/latex/contrib/numprint/numprint.pdf

**Comment by LukasLedvina** [comment]
Ahoj,
s automatikou moc nesouhlasím. Hrozí, že bude fungovat nedobře a pak by tam měl být nějaký backdoor. Spíše linter, který bude kontrolovat, že byla použita makra.

**Comment by LukasLedvina** [comment]
- (mezera)-- se již používá pro oddělení čísla od exponentu - nevhodné.
- ~++
- (nbsp)-- nebude vidět ve zdrojáku

**Comment by MeggyCal** [comment]
asi vyřešeno, zanedlouho nahrajeme do master

**Comment by Werkov** [comment]
Cherry-picknul jsem ještě update jakpsat.tex. Automatické testy prošly všechny, takže nic nebrání releasu.

fks-tex-base                               2.5-30-g542e384

**Comment by LukasLedvina** [comment]
Testoval jsem to a při nastavení angličtiny se mi sází za čárkou mezera, je to v pořádku? Dle [wiki](https://en.wikipedia.org/wiki/English_numerals) by tam ta mezera být neměla.

**Comment by Werkov** [comment]
Asi tam nemůže být obyč čárka, ale asi přímo kód té čárky bez mezery, čili něco jako

    \mathchardef\carka="013B

Netestováno a je to jen tip.

[1] https://github.com/fykosak/fks-texmf/blob/master/tex/latex/fks/fkssugar.sty#L264

**Comment by LukasLedvina** [comment]
Když se to sází normálně, tak v češtině budu sázet:
`1\,023{,}3`

**Comment by LukasLedvina** [comment]
Je toto "typografická norma" [https://en.wikipedia.org/wiki/English_numerals](https://en.wikipedia.org/wiki/English_numerals) ?

**Comment by timkol** [comment]
Closed by #37
