### ISSUE TITLE
Řecké vektory a \mathsf{\alpha}

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#2]
@Pikoš
úprava přidávající řecké vektory stále něco rozbíjí.

Následující kód:
\documentclass{article}
%\usepackage{fkssugar}
\begin{document}
$\mathsf{\alpha}, \mathsf{\beta}, \mathsf{\gamma}$
$\mathbf{\alpha}, \mathbf{\beta}, \mathbf{\gamma}$
\end{document}
funguje. Po odkomentování fkssugar se místo řeckých písmenek objeví nesmysl.

Je otázka, zda takové příkazy mají smysl, ale nelíbí se mi něco rozbíjet.

**Comment by LukasLedvina** [comment]
@Werkov 
> úprava přidávající řecké vektory stále něco rozbíjí.
Předpokládám, že je řeč o 6e419dc1.


isomath.sty and fixmath.sty
>
> Následující kód:
Když to zkusím bez sugaru, tak to sazí prostě alfu, betu a gammu,
nevidím nějakou změnu fontu.

Se sugarem mi to sází nějaké slitky. Ale chyba je převzatá z isomath --
když použiji jen ten, tak to taky dává ty slitky.


> Je otázka, zda takové příkazy mají smysl, ale nelíbí se mi něco rozbíjet.
Pravda. mathsf, asi moc ne. A na mathbf jsou ty vektory nebo ne?

**Comment by LukasLedvina** [comment]
Fixováno ve větvi dev-fkssugar-mathsf: 828cefdc00.

Dokonce se mi povedlo vymítit makro \vectgr a všechny vektory jde sázet pomocí \vect.

**Comment by Werkov** [comment]
Mergeováno do `dev`u a přegeneroval jsem s tím výsledky testu `t004`.

**Comment by timkol** [comment]
$\vect{\alpha}\beta$ vysází i \beta jako vektor.

**Comment by Werkov** [comment]
Dobrá trefa. Přidal jsem na to test a patch níže mi to opravuje.

```
diff --git a/tex/latex/fks/fkssugar.sty b/tex/latex/fks/fkssugar.sty
index df6f68e..bd1c405 100644
--- a/tex/latex/fks/fkssugar.sty
+++ b/tex/latex/fks/fkssugar.sty
@@ -176,7 +176,7 @@
   \renewcommand\omega{#1\fksomega}
 }%
 % swap definitions only for vect macro.
-\newcommand\vect[1]{\sw@pgreekletters\vectgralpha\vectalpha#1}
+\newcommand\vect[1]{\bgroup\sw@pgreekletters\vectgralpha\vectalpha#1\egroup}
 \newcommand\vectgr\vect % only for compatibility reasons
 
 %special for upright pi
 ```

Moc do toho nevidím, tak to možná jde udělat i hezčeji, podívej se prosím na to Lukáši a rovnou to commitni v texmf.base. Dík.

**Comment by Werkov** [comment]
Lukáš patch schválil e-mailem. Mergnuto a releasnuto.
