### ISSUE TITLE
Anglická sazba

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#23]
Sazba patičky, hlavičky úlohy, adresy optimalizovaná pro danou jazykovou mutaci.

Prosím o merge větve dev-meta-lang.

**Comment by LukasLedvina** [comment]
Ještě je potřeba něco dodělat. Pokud nepřijde jazyk v ClassOptions, havaruje překlad.

**Comment by LukasLedvina** [comment]
Opraveno. Pokud není ve fksmeta nastaven jazyk, použije se čeština a vypíše se warning.

**Comment by Werkov** [comment]
Zavírám tuto issue. Nahrazeno #26.
