### ISSUE TITLE
Feature větve v repu

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#24]
Mazat či nemazat nepotřebné (mergnuté) větve.
Pro:

- Udělá to větší pořádek.

Proti

- Někdy je dobré v dané větvi pokračovat s vývojem i po mergi.

**Comment by Auratons** [comment]
Filosofie větví je napsat, co potřebuješ a smazat. Dlouhodobé větve by měly smysl ve chvíli, kdy by byla stabilní větev, dev větev s ne nutně stabilním kódem a třeba ještě něco méně stabilního.

Pokud je daná větev skutečně hotová, tzn. v dané věci se již nebude nic dále podnikat v blízké době, tak jsem pro to to mazat. Nechal bych dev a třeba ten vyfuk-dev.

**Comment by Werkov** [comment]
Větev. Co je větev? Reference jenom malá.

V lokálním repozitáři je to **každého věc**. (Lokálním repozitářem nechť zde myslím jak lokální kopii, tak fork na Githubu.)

Když by se mergeovalo jen přes GUI pull requestů, tak se do centrálního repozitáře ta větev (reference) ani nedostane.

Když by se mergeovalo lokálně tak si tu větev buď stáhnu od někoho (uživatelské repo) nebo si ji sám vytvořím. Zbyvající případ by bylo, kdyby se ta větev přenášela přes ten centrální repozitář. Pak bych ji **po mergi mazal**. A když by se chtělo ve vývoji pokračovat, tak založit novou větev na aktulní špičce mastera (pokračovat ve vývoji po mergi v tom bodě merge je kontraproduktivní, pokud to v budoucnu budu chtít stejně zase mergeovat).

**Comment by LukasLedvina** [comment]
Ahoj, tak jsem to pročistil (vlastně hlavně od vlastních větví :P). Zbyly tam větvě (asi nepotřebné)

- dev-tilde (nenamergovaná, asi duplikuje dev-tilde2)
- dev-tilde2 (namergovaná, ??aktivní??, ale ne moje)
- ficury_vyfuk (namergovaná, ??aktivní??, ale ne moje)

**Comment by Werkov** [comment]
Aha, `git fetch -p`, užitečné.

Smazal jsem Tebou zmíněné větve. (`dev-tilde` byla nahrazena `dev-tilde2`.)

BTW ještě je tam `FoL-debug` z  Tue Dec 4 15:25:03 2012 +0100, řekl bych, že to už bylo taky nahrazeno. Souhlasíš-li, tak ji taky prosím smaž a zavři.

**Comment by LukasLedvina** [comment]
Větev FoL-debug byla určena k tomu, že se (tuším v brožurce) sázelo i to políčko, co se dává databázi a počet platných cifer. Používal jsem to ke korekturám. Lze smazat, pokud korektoři nemají zájem, či to dělají jinak. Nebo udělat systémovější řešení. Navíc těch aktualizací maker je moc, takže to asi už nebude úplně aktuálně použitelné.
