### ISSUE TITLE
Makro \vect vysází v obsahu znak \pi navíc

### ISSUE THREAD

**Issue by xlfds** [fykosak/fks-texmf#27]
Makro \vect v nadpisech dělá:

\section{Matice $\vect P$}

tak se to v nadpisu vysízí podle očekávání:
Matice <tučné P>
a v obsahu se objeví:
Matice <tučné \pi> <tučné P>

**Comment by LukasLedvina** [comment]
Dále 
- Mě `\section{Matice $\vect \pi$}` sází v obsahu Matice <tučné pi><tučné p><normální p>.
- Pak také, pokud je v nadpisu `\vect\alpha`, tak je v obsahu <tučné \pi> navíc.

Problémem bylo, že latex do obsahu vyexpandoval z `\def\pi{#1\fkspi}` to první `\pi`... **!!!!Zabít LaTeX!!!!!**

- Opraveno, že je potřeba používat `\varpi` pro vektorové `\pi`. Matice P je opravená.
