### ISSUE TITLE
\qed je konfliktní s beamrem

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#3]
Toto makro je již definováno v beamer balíku a dělá to potíže.

**Comment by LukasLedvina** [comment]
Fixed dev-fkssugar-qed: 4fcb2248

**Comment by Werkov** [comment]
Makru `\@ifundefined` chyběl druhý argument. Nahradil jsem jej `\providecommand` a mergeoval tohle do `dev`.
