### ISSUE TITLE
Restrukturovat texmf

### ISSUE THREAD

**Issue by Werkov** [fykosak/fks-texmf#30]
- Nejlépe zrušit texmf-fonts (IMO by měly být už zastaralé).
- přesunout strom texmf do podadresáře.
- přesunout testy z texmf.dist do texmf.
- zrušit texmf.dist.
- automatizovat buildící a vydávací proces (Open Build Service, Travis).

- Bude chtít přepsat historii -- možná založit nový repozitář, aby to nemátlo.

Výsledkem by mělo být pohodlnější buildění a čístší struktura obdobná jiným open source projektům (upstream + distribuční/balíčkovací speciality).

**Comment by LukasLedvina** [comment]
Jaký je důvod přepisu historie? Přesun testů, asi největší zásah by šel udělat v rámci jednoho (několika málo) commitu(ů). O emailech jsme se, co vím, dohodli, že až tak nevadí s ohledem na pdf řešení.

**Comment by Werkov** [comment]
Ano, přesun. Pohodlnější hledání v historii (nutnost `git log --follow`) a [`git blame`](http://stackoverflow.com/a/29468810/1351874). Nechám si projít hlavou, co je větší PITA (přepis historie, nesouvislost logů).

**Comment by LukasLedvina** [comment]
A co pro toto použít něco jako `git filter branch` v `texmf.dist` a `git subtree merge` v `texmf`?

Historie se neztratí, testy budou, kde mají být, pak se v rámci třeba jednoho commitu dodělají Makefile a podobně.

**Comment by Werkov** [comment]
Rozjel jsem to ve větvi [texmf-refactoring](https://github.com/fykosak/fks-texmf/tree/texmf-refactoring).

Chybí:
* migrovat testy z texmf.dist, pak nakonfigurovat Travis,
* zrušit texmf.fonts,
* odstranit balíčky embedované z TeXLive (už musí být zastaralé).

**Comment by Werkov** [comment]
Můj cíl: mít to v provozu před úvodním výjezdem (2017-10-13).

Testy na openSUSE se překládají, ale dávají špatné výsledky. Další krok je spouštět je na Travisu.

**Comment by Werkov** [comment]
Vyřešeno v rámci PR #39. Nově builděné balíčky budou verze 2.6 a vyšší.
