### ISSUE TITLE
chybí větev pikos-fonty

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#32]
Ahoj,
proč při migraci z fykosího stroje nebyla migrována větev `pikos-fonty`, která je nezamergovaná a souvisí s #6.
Lukáš

**Comment by Werkov** [comment]
Je [to](https://github.com/fykosak/fks-texmf/tree/pikos-fonty) ono?

**Comment by LukasLedvina** [comment]
Je to ono. Díky.
