### ISSUE TITLE
Podpora anglické sazby

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#4]
V angličtině sázet desetinnou tečku, správné uvozovky, Fig. místo Obr., tan místo tg.

**Comment by LukasLedvina** [comment]
Vyřešeno dev-fkssugar-english: 0672023.

**Comment by LukasLedvina** [comment]
`\fkssug@rczech` nepřepne správně uvozovky.

**Comment by Werkov** [comment]
Upravil jsem testy, aby testovaly jen přepínaní na angličtinu (řeckou abecedu v exponentech jsem extrahoval do samostatného testu); vygeneroval jsem výsledky a mergeoval tohle do `dev`.
