### ISSUE TITLE
Přesun kódu na github

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#8]
@LukasLedvina
Jaký máte názor na přesun texmf na github či založení prázdného repozitáře na githubu a používat jen ten jejich issue tracker?

Mám tu v mailu docela dost nevyřešených připomínek a byl bych nerad, když by se ztratily.

**Comment by LukasLedvina** [comment]
@cevro 
ak sa nemylim tak problem bude asi obdobny ako sa riesil u vydavania makier a to ze su (boli) ulozene emaily orgov.

Prazdny repozitar skludom vytvor tomu nic nebrani.

**Comment by LukasLedvina** [comment]
@Werkov 
Mít texmf jako open-source (což ostatně je už nyní [1]) mě už taky
párkrát napadlo, issue tracker je taky milý bonus. E-maily (a případně
jiné) by se musely před zveřejněním odebrat z historie (`git
filter-branch`).

(Mimochodem jsem na to včera narazil i ve FKSDB, kde sice nejsou hesla,
ale jsou tam nějaká data o účastnících z dávné migrace.)

Jsou-li to jenom e-maily,

**Comment by LukasLedvina** [comment]
@LukasLedvina
založil jsem na gihubu repozitář fks-texmf. Zatím bych jej používal na hlášení závad. O přesunu dat se můžeme ještě pobavit.

Naimportoval jsem tam snad všechny známé chyby.

Ohledně emailů, na které upozorňoval Michal vidím dva pohledy:
  * Emaily bychom měli odstranit (z historie), abychom nebyli spamováni -- myslím, že to tak kritické není; stejně tam jsou už dost staré a do značné míry nepoužívané emaily.
  * Odstraněním souboru signatures.tex zabijeme to, co jsme si slíbili: Staré věci budou přeložitelné makry z té doby.
  * Jiné "osobní" informace tam asi už nejsou, ne?

**Comment by LukasLedvina** [comment]
Diskuse již byla otevřena na [wiki.fykos.cz](https://wiki.fykos.cz/spolecne:texani#temata).

**Comment by Werkov** [comment]
Prolétnutím se mi tamější diskuze zdá již zastaralá, ty podstatné jsi již stejně vypích zde v komentářích.

Názor na e-maily mi uzrál, abychom je tam nechali (v těch historických commitech), jak navrhuješ. Krom nepoužívanosti si stejně e-maily aktivní orgů boti najdou v PDFkách vzoráků.

Úpravu workflow a buildovacích skriptů bych si vzal na hackathon (cc @cevro).

**Comment by Werkov** [comment]
Status: už bych to sem dal jako ruční mirror, ale nemůžu zrušit staré repo, neboť je potřeba(?) na Astrid, kde se z něj buildí ZIP archiv pro Windowsáky. 

Úpravu workflow a buildění řešit ve #12.

**Comment by LukasLedvina** [comment]
Nemůže Astrid pullovat z githubu?

**Comment by Werkov** [comment]
Může. To co to blokuje je rozhraní volání hooků (tj. to co jsem teď upravoval pro FKSDB).
Astrid přijímá pomocí HTTP autentizace, Github posílá vlastní HTTP hlavičky pro autentizaci.
Workaround před úpravou autentizace by bylo ruční volání buildů.

**Comment by timkol** [comment]
A co nevydávat zipbally pomocí Astrid, ale pomocí Travis CI na Github, viz https://docs.travis-ci.com/user/deployment/releases/

**Comment by Werkov** [comment]
Prakticky hotovo. Nedodělek oddělen do #41.
