### ISSUE TITLE
Abbreviate High School as HS

### ISSUE THREAD

**Issue by rzehumat** [fykosak/fks-texmf#83]
Several school names include `High School`. This is impractical for the purpose of batches and any printed tables with results, since it often causes the name to split on two lines, which does not look good if there are many of them. 
Abbreviating it as `HS` would be nice IMO. This would be nice to happen before generating the file with results (i.e. `batchN/results/vysledkyN-*.tex` would already be abbreviated). 

**Example**:
Current version
```
1. & Alice Mackenzie & Wonderland High School, Wonderland & -- & -- & -- & -- & -- & -- & -- & -- & -- & 7 &\hotfix{x}& y\\ 
```

Desired
```
1. & Alice Mackenzie & Wonderland HS, Wonderland & -- & -- & -- & -- & -- & -- & -- & -- & -- & 7 &\hotfix{x}& y\\ 
```

**Comment by rzehumat** [comment]
We can do such stuff -- there already are some names with `HS`. The same is already working with the Czech `Gymnázium` denoted as `G`.

**Comment by rzehumat** [comment]
Or is it more like `fksdb` issue?

**Comment by sstenchlak** [comment]
This is a data issue in FKSDB. I suggest abbreviating those words (High School -> HS) in the `school.name_abbrev` field, which is used in brochures. (the original names would be unaffected)

@cevro do you agree?
