### ISSUE TITLE
Testování maker

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-texmf#9]
Testoval jsem generování vzorů z jiné větvě:

To, že se nepřeložil `t006-qed.tex` ne naprosto v pořádku, ale vy výpisy výše jsou značně podezřelé a ta `t007` a `t009` se nepřeložily.

```
$ make test-results BRANCH_DEV=dev-fkssugar-english
./tests/make-result.sh dev-fkssugar-english tests/source/t001-empty.tex ./tests/exp-res
fatal: Not a valid object name
tar: Toto pravděpodobně není tar archiv
tar: Končí se chybovým kódem, protože byly zaznamenány chyby
./tests/make-result.sh dev-fkssugar-english tests/source/t007-english.tex ./tests/exp-res
fatal: Not a valid object name
tar: Toto pravděpodobně není tar archiv
tar: Končí se chybovým kódem, protože byly zaznamenány chyby
./tests/make-result.sh dev-fkssugar-english tests/source/t009-english-c.tex ./tests/exp-res
fatal: Not a valid object name
tar: Toto pravděpodobně není tar archiv
tar: Končí se chybovým kódem, protože byly zaznamenány chyby
./tests/make-result.sh dev-fkssugar-english tests/source/t006-qed.tex ./tests/exp-res
fatal: Not a valid object name
tar: Toto pravděpodobně není tar archiv
tar: Končí se chybovým kódem, protože byly zaznamenány chyby
Can't compile tests/source/t006-qed.tex
Makefile:44: návod pro cíl „out/tests/t006-qed.pdf“ selhal
make: *** [out/tests/t006-qed.pdf] Chyba 1
```

**Comment by Werkov** [comment]
Upravil jsem všechny běhy testů tak, aby nepracovali s větví, ale prostě `texmf` adresářem. Zatím je to ve větvi `heads/test/graphical/michal/wip`, ale hodlám to mergeovat do mastera. Pak se tohle může zavřít.

**Comment by Werkov** [comment]
Testy aktualizovány, commitnuty do `master` a pushnuto na serveru. Můžeš prosím otestovat, že ti testy, jak jsem je vygeneroval passují? (`make test` přičemž v `components/texmf.base` checkoutni do `dev` (f6b5b44)).

**Comment by LukasLedvina** [comment]
Test 010-qed havaruje:

```
=== ./out/tests/t010-qed-1.log ===
Shapes are different. (5500, 4250, 3) (5847, 4134, 3)
======
Test ./tests/exp-res/t010-qed-1.png/appearance failed (page t010-qed.tex).
Test ./tests/exp-res/t010-qed-1.png/appearance failed.

```

Nejspíše jde o chybné nastavení velikosti papíru. Je tam zakomentovaný řádek `\usepackage[a4paper]{geometry}`. @Werkov jaký je důvod k zakomentování?

**Comment by Werkov** [comment]
Je to chyba. Opravil jsem. Pokud Ti testy chodí, můžeš to zavřít.
