### ISSUE TITLE
[yearbook] cover není v makrech

### ISSUE THREAD

**Issue by rzehumat** [fykosak/fks-texmf#95]
Zdá se mi, že `cover.tex` není v tomto balíčku maker a celkově je to tak trochu bordel, co se jen kopíruje z ročníku do ročníku.

Uvažuji, zda by mělo smysl to přidat do balíčku maker, třeba jako documentclass `fksyearbook-cover.cls` nebo tak něco. Nebo je to příliš námahy za drobnost?

**Comment by Headary** [comment]
Teď je prostě všechno v jednom souboru, když to chceš změnit, tak není potřeba řešit zpětnou kompatibilitu a není potřeba lézt do maker a vytvářet novou verzi. A vzhledem k tomu, že to je jeden soubor za rok, tak nevidím moc smysl pro to vytvářet novou class, když už máme ustálené soubory, které to vytváří. Jediné pozitivu, co bych viděl, tak by bylo sdílení nových features mezi semináři, ale těch je tak málo, že je jednoduší je překopírovat.
